"""Initial migration.

Revision ID: 2bb080d5f6fb
Revises: 
Create Date: 2021-12-10 20:42:09.810696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bb080d5f6fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collectible',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('metadata_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['metadata_id'], ['metadata.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collectible')
    # ### end Alembic commands ###
